---

- name: set up web services
  # TODO Remove when Busywork is decommissioned
  hosts: all
  vars:
    ftp_dir: /home/ubuntu/ftp
  roles:
    - ufw
    - nginx
    - docker
    # TODO Remove when Busywork is decommissioned
    - ftp
