version: '3'
services:
  server:
    build: .
    image: library-staging-ftp:latest
    privileged: true
    volumes:
      - /usr/share/nginx/html/packages.qiime2.org/qiime2:/home/ftpusers
      - {{ ftp_dir }}/tls:/etc/ssl/private
    ports:
      - "21:21"
      - "30000-30099:30000-30099"
    environment:
      PUBLICHOST: {{ ansible_host }}
      FTP_USER_NAME: {{ FTP_USER_NAME }}
      FTP_USER_PASS: {{ FTP_USER_PASS }}
      FTP_USER_HOME: {{ FTP_USER_HOME }}
      FTP_USER_UID: {{ FTP_USER_UID }}
      FTP_USER_GID: {{ FTP_USER_GID }}
